# Generated by Django 4.1 on 2022-09-02 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grow', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Plants',
            new_name='Plant',
        ),
    ]
