# Generated by Django 4.1.1 on 2022-09-09 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grow', '0003_alter_blog_plants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='plants',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='grow.plant'),
        ),
    ]
